#!/usr/bin/env bash
# accept two arguments
func ()
{
  if [ "$#" -eq 2 ]
  then
        subdomain="$2"
        subdomain+="."
        subdomain+="$1"
        record=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' |tail -1 | awk '{print $4}')
        address=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
        echo The subdomain "$subdomain" is a "$record" record and points to "$address"
  fi
}

if [ "$#" -eq 2 ]
then
        func "$1" "$2"
elif [ "$#" -eq 1 ]
then
        func "$1" 'www'
        func "$1" 'lb-01'
        func "$1" 'web-01'
        func "$1" 'web-02'
fi
