#!/usr/bin/env bash
# Transfer a file to the server
if [ $# -lt 4 ]
  then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  path=$1
  user=$3
  ip=$2
  pathkey=$4
  scp -o StrictHostKeyChecking=no -i "${pathkey}" "${path}" "${user}"@"${ip}":~
fi
