#!/usr/bin/env bash
# Install and configure nginx web server
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y nginx
# sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
# echo 'Hello World!' > /var/www/html/index.html
