#!/usr/bin/env bash
# Install and configure nginx web server
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y nginx
sudo service nginx start
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
