#!/usr/bin/env bash
# Install and configure nginx web server
sudo apt-get update
sudo apt-get upgrade
sudo apt install -y nginx
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
