#!/usr/bin/env bash
# Install nginx and redirects the url /redirect_me
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
#sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me\/*$ https:\/\/www.youtube.com\/watch\?v\=QH2\-TGUlwu4 permanent;/" /etc/nginx/sites-enabled/default
sed -i s/"# SSL configuration"/"\tlocation \/redirect_me \{\n\t\treturn 301 https:\/\/www.youtbue.com;\n\t\}\n\t# SSL configuration"/ /etc/nginx/sites-enabled/default
sudo service nginx reload
