#!/usr/bin/env bash
# Install nginx and create redirect directory
sudo apt-get -y update
sudo apt-get -y ugrade
sudo apt install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v\=QH2\-TGUlwu4 permanent;/g" /etc/nginx/sites-enabled/default
sudo touch /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i 's/index.nginx-debian.html;/index.nginx-debian.html;\n\terror_page 404 \/custom_404.html;\n\tlocation \= \/custom_404.html \{\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t\}/' /etc/nginx/sites-enabled/default
sudo service nginx start
