#!/usr/bin/env bash
# Ensures nginx is listening on port 80 of all server's active IPv4 IPs
sudo sed -i -E '/^\s*listen [0-9]+/c listen 80 default_server;' /etc/nginx/sites-enabled/default
sed -i '/^\s*listen \[::\]/c  listen \[::\]:80;' /etc/nginx/sites-enabled/default
sudo service nginx restart
