#!/usr/bin/env bash
# display
i="1";
for ((i=1; i < 101; i++));
do
	if (( "$i" % 15 == 0 ))
	then
		echo "FizzBuzz";
	elif (( "$i" % 5 == 0 ))
	then
		echo "Buzz";
	elif (( "$i" % 3 == 0))
	then
		echo "Fizz";
	else
		echo "$i";
	fi
done
