#!/usr/bin/env bash
# displays bad luck on 4th loop, good luck on 8th loop and Best School for other iterations
i="0";
while [ "$i" -ne 10 ]
do
if [ "$i" -eq 3 ]
then
	echo "bad luck";
elif [ "$i" -eq 7 ]
then
	echo "good luck";
else
	echo "Best School";
fi
((i++));
done;
