#!/usr/bin/env bash
# displays
i="1";
while [ "$i" -lt 21 ]
do
	echo "Best School";
case "$i" in
4)
echo "bad luck from china";
;;
9)
echo "bad  luck from Japan";
;;
17)
echo "bad luck from Italy";
;;
esac
((i++));
done;
