#!/usr/bin/env bash
# configure nginx to be running as nginx user
# configures nginx to listening on all active IPs on port 8080

sudo service nginx stop
sudo sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-enabled/default

# update nginx user in nginx.conf file
sudo sed -i 's/user www-data;/user ngnix;/g' /etc/nginx/nginx.conf

# Restart nginx
sudo service nginx start
