#!/usr/bin/env bash
# configure nginx to be running as nginx
chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/user www-data/user ngnix/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
