#!/usr/bin/env bash
# configure nginx to be running as nginx user
# configures nginx to listening on all active IPs on port 8080

sudo service nginx stop
chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/listen\s*80/listen 8080/g" /etc/nginx/sites-enabled/default
# update nginx user in nginx.conf file
sudo sed -i "s/user www-data/user ngnix/" /etc/nginx/nginx.conf
# Restart nginx
sudo systemctl restart nginx.service

