#!/usr/bin/env bash
# configure nginx to be running as nginx
sudo service nginx stop
chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/listen\s*80/listen 8080/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/user www-data/user ngnix/" /etc/nginx/nginx.conf
sudo systemctl restart nginx.service
